create database SSIS

use SSIS

CREATE TABLE test (
	"AGE" DECIMAL(38, 0) , 
	"WORKCLASS" VARCHAR(17), 
	"FNLWGT" DECIMAL(38, 0) , 
	"EDUCATION" VARCHAR(13) , 
	"EDUCATION.NUM" DECIMAL(38, 0) , 
	"MARITAL.STATUS" VARCHAR(22) , 
	"OCCUPATION" VARCHAR(18), 
	"RELATIONSHIP" VARCHAR(15) , 
	"RACE" VARCHAR(19) , 
	"SEX" VARCHAR(7) , 
	"CAPITAL.GAIN" DECIMAL(38, 0) , 
	"CAPITAL.LOSS" DECIMAL(38, 0) , 
	"HOURS.PER.WEEK" DECIMAL(38, 0) , 
	"NATIVE.COUNTRY" VARCHAR(27), 
	"TARGET" VARCHAR(7) 
);


